### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by armory09** [frederiksen/chrome-platform-bridge#3]
Hi @frederiksen ,

Thank you for this awesome example on how to use native messaging.
Sorry for this, I just want to know, how can i debug the project? 
a link will help.

Thank you so much
Jonathan

**Comment by frederiksen** [comment]
What layer do you want to debug?

If it is the NM host - you can start the example (then the NM host will start) and then attach a debugger.

If you want to debug the extension: https://developer.chrome.com/extensions/tut_debugging

**Comment by armory09** [comment]
Thank you for the response sir. This will help me a lot.
Is it ok if i leave this one open for the meantime, just in case got some follow up question? 

Thanks

**Comment by armory09** [comment]
Hi @frederiksen ,

Is it advisable to only use console app as host when using native messaging?
I just notice whenever i had unhandled exception even though i have try catch.
The console app still crash and close, do we have any other options?

I tried to use Worker Service but couldn't make it work :grimacing:
One more thing is, when an exception throw inside Task.Run, its not rethrowing the exception and the result i cant send it back to the web app.

Hoping to have a suggestion from you.


**UPDATE:** 
Found the issue, because somewhere on the host app, i was calling Console.Write, when i removed it everything works perfect. 😸 

Jonathan

**Comment by armory09** [comment]
Hi @frederiksen ,

Good day sir,
Hope you are doing well.
I just want to ask, when using your installer where does it add the registry? 
Based on the `installer.wxs` it should be in `HKEY_LOCAL_MACHINE`.
But when i tried to check on it, it doesn't show there

`HKEY_LOCAL_MACHINE`
![image](https://user-images.githubusercontent.com/6113947/79106667-86a11180-7da5-11ea-8cc5-aaade4d85892.png)


`HKEY_CURRENT_USER`
![image](https://user-images.githubusercontent.com/6113947/79106731-a6d0d080-7da5-11ea-8983-480b24f0ea35.png)


NOTE: Even thou it doesn't show, it still works 😄 
I'm just curious how is that?

Thanks,
Jonathan
